#!/bin/sh

set -x
set -e

. debian/tests/util

username="smbtest$$"
password="$$"
netbios_name="netbios$$"
# make sure we are starting fresh
rm -f "/var/log/samba/log.${netbios_name}" 2>/dev/null || :
storagedir=$(mktemp -d)
chmod 1777 "${storagedir}"
testfile="hello.txt"
echo hello >  "${storagedir}/${testfile}"

cleanup() {
    set +e
    if [ -d "${storagedir}" ]; then
        rm -rf "${storagedir}"
    fi
}

trap cleanup EXIT

# prepare a per-user config file snippet
cat > /etc/samba/"${username}".conf <<EOF
[global]
[storage]
    path = ${storagedir}
    read only = no
EOF
# [global] section changes:
# - include the per-user config file
# - set netbios name to something we can check later to verify the %m macro
sed -r -i "/^\[global\]$/a config file = \/etc\/samba\/%U.conf" /etc/samba/smb.conf
sed -r -i "/^\[global\]$/a netbios name = ${netbios_name}" /etc/samba/smb.conf
systemctl reload smbd

add_user "${username}" "${password}"

echo "Listing //localhost/${testfile} as user ${username}"
smbclient //localhost/storage -U "${username}"%"${password}" --command "ls ${testfile}"

echo "Listing //localhost/${testfile} as anonymous should fail, because then the share doesn't exist"

result=0
smbclient //localhost/storage -N --command "ls ${testfile}" || result=$?
if [ ${result} -eq 0 ]; then
    echo "FAIL, this should not have worked"
fi

echo "Checking if connection attempts generated a logfile log.${netbios_name}"
ls -l "/var/log/samba/log.${netbios_name}"
